// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExecuteCommand(arg1: string): Promise<Record<string, any>>;

export function GetStatus(): Promise<Record<string, any>>;

export function HealthCheck(): Promise<Record<string, any>>;
