// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExecuteCommand(arg1) {
  return window['go']['main']['AgentHarness']['ExecuteCommand'](arg1);
}

export function GetStatus() {
  return window['go']['main']['AgentHarness']['GetStatus']();
}

export function HealthCheck() {
  return window['go']['main']['AgentHarness']['HealthCheck']();
}
