// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function EmitEvent(arg1, arg2) {
  return window['go']['main']['App']['EmitEvent'](arg1, arg2);
}

export function GetAppName() {
  return window['go']['main']['App']['GetAppName']();
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetEnv(arg1) {
  return window['go']['main']['App']['GetEnv'](arg1);
}

export function GetHomeDir() {
  return window['go']['main']['App']['GetHomeDir']();
}

export function GetPlatform() {
  return window['go']['main']['App']['GetPlatform']();
}

export function GetWorkingDir() {
  return window['go']['main']['App']['GetWorkingDir']();
}

export function MessageDialog(arg1, arg2) {
  return window['go']['main']['App']['MessageDialog'](arg1, arg2);
}

export function OpenConfigFile() {
  return window['go']['main']['App']['OpenConfigFile']();
}

export function OpenFileDialog(arg1) {
  return window['go']['main']['App']['OpenFileDialog'](arg1);
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}

export function SaveFileDialog(arg1, arg2) {
  return window['go']['main']['App']['SaveFileDialog'](arg1, arg2);
}

export function WindowClose() {
  return window['go']['main']['App']['WindowClose']();
}

export function WindowFullscreen() {
  return window['go']['main']['App']['WindowFullscreen']();
}

export function WindowGetPosition() {
  return window['go']['main']['App']['WindowGetPosition']();
}

export function WindowGetSize() {
  return window['go']['main']['App']['WindowGetSize']();
}

export function WindowIsFullscreen() {
  return window['go']['main']['App']['WindowIsFullscreen']();
}

export function WindowIsMaximised() {
  return window['go']['main']['App']['WindowIsMaximised']();
}

export function WindowMaximise() {
  return window['go']['main']['App']['WindowMaximise']();
}

export function WindowMinimise() {
  return window['go']['main']['App']['WindowMinimise']();
}

export function WindowSetPosition(arg1, arg2) {
  return window['go']['main']['App']['WindowSetPosition'](arg1, arg2);
}

export function WindowSetSize(arg1, arg2) {
  return window['go']['main']['App']['WindowSetSize'](arg1, arg2);
}

export function WindowToggleMaximise() {
  return window['go']['main']['App']['WindowToggleMaximise']();
}

export function WindowUnfullscreen() {
  return window['go']['main']['App']['WindowUnfullscreen']();
}

export function WindowUnmaximise() {
  return window['go']['main']['App']['WindowUnmaximise']();
}
