// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function EmitEvent(arg1:string,arg2:Array<any>):Promise<void>;

export function GetAppName():Promise<string>;

export function GetAppVersion():Promise<string>;

export function GetEnv(arg1:string):Promise<string>;

export function GetHomeDir():Promise<string>;

export function GetPlatform():Promise<string>;

export function GetWorkingDir():Promise<string>;

export function MessageDialog(arg1:string,arg2:string):Promise<void>;

export function OpenConfigFile():Promise<void>;

export function OpenFileDialog(arg1:string):Promise<string>;

export function OpenURL(arg1:string):Promise<void>;

export function SaveFileDialog(arg1:string,arg2:string):Promise<string>;

export function WindowClose():Promise<void>;

export function WindowFullscreen():Promise<void>;

export function WindowGetPosition():Promise<number|number>;

export function WindowGetSize():Promise<number|number>;

export function WindowIsFullscreen():Promise<boolean>;

export function WindowIsMaximised():Promise<boolean>;

export function WindowMaximise():Promise<void>;

export function WindowMinimise():Promise<void>;

export function WindowSetPosition(arg1:number,arg2:number):Promise<void>;

export function WindowSetSize(arg1:number,arg2:number):Promise<void>;

export function WindowToggleMaximise():Promise<void>;

export function WindowUnfullscreen():Promise<void>;

export function WindowUnmaximise():Promise<void>;
