// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetBackgroundColor():Promise<string>;

export function GetConfig():Promise<Record<string, any>>;

export function GetConfigDir():Promise<string>;

export function GetConfigPath():Promise<string>;

export function GetConfigValue(arg1:string):Promise<any>;

export function GetFontFamily():Promise<string>;

export function GetFontSize():Promise<number>;

export function GetKeymaps():Promise<Record<string, any>>;

export function GetShell():Promise<string>;

export function GetShellArgs():Promise<Array<string>>;

export function GetWorkingDirectory():Promise<string>;

export function OpenConfigInEditor():Promise<void>;

export function ProfileConfig(arg1:string):Promise<Record<string, any>>;

export function SetConfig(arg1:Record<string, any>):Promise<void>;

export function SetConfigValue(arg1:string,arg2:any):Promise<void>;

export function Subscribe(arg1:any):Promise<void>;
