// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetBackgroundColor() {
  return window['go']['main']['ConfigManager']['GetBackgroundColor']();
}

export function GetConfig() {
  return window['go']['main']['ConfigManager']['GetConfig']();
}

export function GetConfigDir() {
  return window['go']['main']['ConfigManager']['GetConfigDir']();
}

export function GetConfigPath() {
  return window['go']['main']['ConfigManager']['GetConfigPath']();
}

export function GetConfigValue(arg1) {
  return window['go']['main']['ConfigManager']['GetConfigValue'](arg1);
}

export function GetFontFamily() {
  return window['go']['main']['ConfigManager']['GetFontFamily']();
}

export function GetFontSize() {
  return window['go']['main']['ConfigManager']['GetFontSize']();
}

export function GetKeymaps() {
  return window['go']['main']['ConfigManager']['GetKeymaps']();
}

export function GetShell() {
  return window['go']['main']['ConfigManager']['GetShell']();
}

export function GetShellArgs() {
  return window['go']['main']['ConfigManager']['GetShellArgs']();
}

export function GetWorkingDirectory() {
  return window['go']['main']['ConfigManager']['GetWorkingDirectory']();
}

export function OpenConfigInEditor() {
  return window['go']['main']['ConfigManager']['OpenConfigInEditor']();
}

export function ProfileConfig(arg1) {
  return window['go']['main']['ConfigManager']['ProfileConfig'](arg1);
}

export function SetConfig(arg1) {
  return window['go']['main']['ConfigManager']['SetConfig'](arg1);
}

export function SetConfigValue(arg1, arg2) {
  return window['go']['main']['ConfigManager']['SetConfigValue'](arg1, arg2);
}

export function Subscribe(arg1) {
  return window['go']['main']['ConfigManager']['Subscribe'](arg1);
}
