// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddServer(arg1) {
  return window['go']['main']['MCPAggregator']['AddServer'](arg1);
}

export function CallTool(arg1, arg2) {
  return window['go']['main']['MCPAggregator']['CallTool'](arg1, arg2);
}

export function GetTelemetry() {
  return window['go']['main']['MCPAggregator']['GetTelemetry']();
}

export function ListServers() {
  return window['go']['main']['MCPAggregator']['ListServers']();
}

export function ListTools() {
  return window['go']['main']['MCPAggregator']['ListTools']();
}

export function ListToolsJSON() {
  return window['go']['main']['MCPAggregator']['ListToolsJSON']();
}

export function RegisterTool(arg1) {
  return window['go']['main']['MCPAggregator']['RegisterTool'](arg1);
}
