// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddServer(arg1:Record<string, any>):Promise<void>;

export function CallTool(arg1:string,arg2:Record<string, any>):Promise<Record<string, any>>;

export function GetTelemetry():Promise<Record<string, any>>;

export function ListServers():Promise<Array<Record<string, any>>>;

export function ListTools():Promise<Array<main.MCPTool>>;

export function ListToolsJSON():Promise<string>;

export function RegisterTool(arg1:main.MCPTool):Promise<void>;
