// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {time} from '../models';

export function CloseAll():Promise<void>;

export function CloseSession(arg1:string):Promise<void>;

export function CreateSession(arg1:string,arg2:Array<string>,arg3:string,arg4:number,arg5:number,arg6:string):Promise<Record<string, any>>;

export function GetSession(arg1:string):Promise<Record<string, any>>;

export function ListSessions():Promise<Array<Record<string, any>>>;

export function ResizeSession(arg1:string,arg2:number,arg3:number):Promise<void>;

export function SetRuntime(arg1:main.App):Promise<void>;

export function WaitUntilExit(arg1:string,arg2:time.Duration):Promise<void>;

export function WriteData(arg1:string,arg2:string):Promise<void>;
