// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseAll() {
  return window['go']['main']['SessionManager']['CloseAll']();
}

export function CloseSession(arg1) {
  return window['go']['main']['SessionManager']['CloseSession'](arg1);
}

export function CreateSession(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['SessionManager']['CreateSession'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function GetSession(arg1) {
  return window['go']['main']['SessionManager']['GetSession'](arg1);
}

export function ListSessions() {
  return window['go']['main']['SessionManager']['ListSessions']();
}

export function ResizeSession(arg1, arg2, arg3) {
  return window['go']['main']['SessionManager']['ResizeSession'](arg1, arg2, arg3);
}

export function SetRuntime(arg1) {
  return window['go']['main']['SessionManager']['SetRuntime'](arg1);
}

export function WaitUntilExit(arg1, arg2) {
  return window['go']['main']['SessionManager']['WaitUntilExit'](arg1, arg2);
}

export function WriteData(arg1, arg2) {
  return window['go']['main']['SessionManager']['WriteData'](arg1, arg2);
}
